
package br.com.fiap.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWeb", targetNamespace = "http://ws.exemplos.fiap.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWeb {


    /**
     * 
     * @param aluno
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "novo", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.Novo")
    @ResponseWrapper(localName = "novoResponse", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.NovoResponse")
    @Action(input = "http://ws.exemplos.fiap.br/AlunoWeb/novoRequest", output = "http://ws.exemplos.fiap.br/AlunoWeb/novoResponse")
    public String novo(
        @WebParam(name = "aluno", targetNamespace = "")
        Aluno aluno);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.ws.client.Aluno>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.ListarResponse")
    @Action(input = "http://ws.exemplos.fiap.br/AlunoWeb/listarRequest", output = "http://ws.exemplos.fiap.br/AlunoWeb/listarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplos.fiap.br/AlunoWeb/listar/Fault/Exception")
    })
    public List<Aluno> listar()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAutenticado", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.IsAutenticado")
    @ResponseWrapper(localName = "isAutenticadoResponse", targetNamespace = "http://ws.exemplos.fiap.br/", className = "br.com.fiap.ws.client.IsAutenticadoResponse")
    @Action(input = "http://ws.exemplos.fiap.br/AlunoWeb/isAutenticadoRequest", output = "http://ws.exemplos.fiap.br/AlunoWeb/isAutenticadoResponse")
    public boolean isAutenticado();

}
